# Generated by Django 5.2.4 on 2025-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_created_at_city_humidity_city_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_user_request',
            field=models.BooleanField(default=False),
        ),
    ]
