# Generated by Django 5.2.4 on 2025-07-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_is_user_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='temp_max',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temp_min',
        ),
    ]
